export const blog_data = [
  {
    article_id: "313a47473ba6b008c74c7b5def46442c",
    title:
      "Marcus Stroman reports to Yankees camp and insists he won't go to the bullpen",
    link: "https://www.romesentinel.com/ap/sports/marcus-stroman-reports-to-yankees-camp-and-insists-he-wont-go-to-the-bullpen/article_ea53194c-28ca-507c-8d08-3fcd78549e4d.html",
    keywords: null,
    creator: null,
    video_url: null,
    description:
      "Marcus Stroman has reported to New York Yankees spring training after missing the first two days of workouts and said he will refuse to pitch out of the bullpen. Stroman repeated “I'm a starter” seven times in a 13-second span...",
    content: "ONLY AVAILABLE IN PAID PLANS",
    pubDate: "2025-02-14 18:11:00",
    pubDateTZ: "UTC",
    image_url:
      "https://bloximages.chicago2.vip.townnews.com/romesentinel.com/content/tncms/assets/v3/editorial/4/26/4268520b-558e-5762-885d-5d9bf8c281c7/67ae8a1d0f13d.image.jpg?resize=300%2C200",
    source_id: "romesentinel",
    source_priority: 38985,
    source_name: "Romesentinel",
    source_url: "https://www.romesentinel.com",
    source_icon: "https://i.bytvi.com/domain_icons/romesentinel.jpg",
    language: "english",
    country: ["united states of america"],
    category: ["sports"],
    ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
    ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
    duplicate: true,
  },
  {
    article_id: "b71c94dab9cc3e5be78387ad81da8080",
    title: "Gottesdienst für Betroffene des Münchner Anschlags",
    link: "https://www.nordbayern.de/bayern/gottesdienst-fur-betroffene-des-munchner-anschlags-1.14581193",
    keywords: null,
    creator: null,
    video_url: null,
    description:
      "München - Nach dem Auto-Anschlag mit knapp 40 Verletzten in München soll es zu Beginn der neuen Woche einen Gottesdienst für Betroffene, Angehörige und Einsatzkräfte geben.",
    content: "ONLY AVAILABLE IN PAID PLANS",
    pubDate: "2025-02-14 18:11:00",
    pubDateTZ: "UTC",
    image_url:
      "https://images.nordbayern.de/image/contentid/policy:1.14581194:1739556750/ImportDpaPicFile745jpg.jpg?%24p%24f%24h%24m%24w=710b0b9&f=16%3A9&h=816&m=FIT&w=1680",
    source_id: "nordbayern",
    source_priority: 25970,
    source_name: "Nordbayern",
    source_url: "https://www.nordbayern.de",
    source_icon: "https://i.bytvi.com/domain_icons/nordbayern.png",
    language: "german",
    country: ["germany"],
    category: ["top"],
    ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
    ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
    duplicate: true,
  },
  {
    article_id: "a91c080ebbb672038f4a9aaff9ab8c39",
    title: "JKP Raid Bookstores, Seize 688 Books Linked To JeI",
    link: "https://kashmirobserver.net/2025/02/14/jkp-raid-bookstores-seize-688-books-linked-to-jei/",
    keywords: ["local", "jamaat-e-islami", "news"],
    creator: ["Observer News Service"],
    video_url: null,
    description:
      "Jammu and Kashmir Police have allegedly seized literature affiliated with Jamaat-e-Islami (JeI), a religious-political organisation, which has been banned in Jammu and Kashmir for the last six years. Police teams arrived at several bookshops in the city centre and seized over 650 books, officials said.",
    content: "ONLY AVAILABLE IN PAID PLANS",
    pubDate: "2025-02-14 18:11:00",
    pubDateTZ: "UTC",
    image_url:
      "https://kashmirobserver.net/wp-content/uploads/2024/07/JK-Police-Logo-1.jpg",
    source_id: "kashmirobserver",
    source_priority: 596003,
    source_name: "Kashmir Observer",
    source_url: "https://kashmirobserver.net",
    source_icon: "https://i.bytvi.com/domain_icons/kashmirobserver.jpg",
    language: "english",
    country: ["india"],
    category: ["top"],
    ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
    ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
    duplicate: true,
  },
  {
    article_id: "26e83c2b21eefdf4d59494c742b7268b",
    title:
      "البحرية الملكية توقف قاربا على متنه 6 مهاجرين سريين قبالة سواحل الحسيمة",
    link: "https://dalil-rif.com/permalink/34836.html",
    keywords: ["الواجهة"],
    creator: null,
    video_url: null,
    description:
      "أوقفت البحرية الملكية، صباح اليوم الجمعة 14 فبراير حوالي الساعة الثامنة، قاربا مطاطيا كان على متنه ستة أشخاص يعتزمون الهجرة السرية عبر سواحل الحسيمة.وتمت إحالة",
    content: "ONLY AVAILABLE IN PAID PLANS",
    pubDate: "2025-02-14 18:11:00",
    pubDateTZ: "UTC",
    image_url:
      "https://dalil-rif.com/thumbnail.php?file=BAHRI_427605102.png&size=article_large",
    source_id: "dalil_rif",
    source_priority: 2935354,
    source_name: "شبكة دليل الريف",
    source_url: "https://dalil-rif.com",
    source_icon: "https://i.bytvi.com/domain_icons/dalil_rif.png",
    language: "arabic",
    country: ["morocco"],
    category: ["top"],
    ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
    ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
    duplicate: false,
  },
  {
    article_id: "5a7e7c5622f81720deab6ed3030b2a36",
    title:
      "Moneyspire Unveils Latest Software Innovations to Transform Personal Finance Management",
    link: "https://www.prnewswire.com/news-releases/moneyspire-unveils-latest-software-innovations-to-transform-personal-finance-management-302377247.html",
    keywords: [
      "computer software",
      "banking & financial services",
      "computer & electronics",
      "fnt",
      "stw",
      "financial technology",
      "cpr",
      "fin",
    ],
    creator: null,
    video_url: null,
    description:
      "LAKEWOOD, Calif., Feb. 14, 2025 /PRNewswire/ -- Moneyspire, a leading provider of personal finance software, proudly announces the launch of its latest software release for 2025, designed to make financial management more intuitive, efficient, and secure for users worldwide. This new...",
    content: "ONLY AVAILABLE IN PAID PLANS",
    pubDate: "2025-02-14 18:11:00",
    pubDateTZ: "UTC",
    image_url:
      "https://mma.prnewswire.com/media/2620729/Moneyspire_Inc_Icon.jpg?p=original",
    source_id: "cision",
    source_priority: 1625,
    source_name: "Pr Newswire",
    source_url: "https://www.prnewswire.com",
    source_icon: "https://i.bytvi.com/domain_icons/cision.jpg",
    language: "english",
    country: ["united states of america"],
    category: ["business"],
    ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
    ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
    duplicate: false,
  },
  {
    article_id: "1594f7000a0a83547794dd8b84a35457",
    title:
      "New UK snow maps show 12 cities to escape 446-mile barrage on Sunday - check your area",
    link: "https://www.express.co.uk/news/weather/2014699/uk-snow-maps-cities-sunday-met-office",
    keywords: ["weather"],
    creator: ["Astha Saxena"],
    video_url: null,
    description:
      "Areas from Inverness to Birmingham are likely to experience snow showers on Sunday as the temperatures plummet to 0C in some areas.",
    content: "ONLY AVAILABLE IN PAID PLANS",
    pubDate: "2025-02-14 18:11:00",
    pubDateTZ: "UTC",
    image_url:
      "https://cdn.images.express.co.uk/img/dynamic/153/590x/2014699_1.jpg",
    source_id: "expresscouk",
    source_priority: 1139,
    source_name: "Express",
    source_url: "https://www.express.co.uk",
    source_icon: "https://i.bytvi.com/domain_icons/expresscouk.png",
    language: "english",
    country: ["united kingdom"],
    category: ["environment"],
    ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
    ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
    duplicate: false,
  },
  {
    article_id: "933d5e6957725b4f3e229af049c554e0",
    title:
      "Salmon Arm woman loses licence after admitting to drinking on 'lunch break'",
    link: "https://www.kelownacapnews.com/news/salmon-arm-woman-loses-licence-after-admitting-to-drinking-on-lunch-break-7823531",
    keywords: null,
    creator: ["Heather Black"],
    video_url: null,
    description: "Confessed to having 'several beers, and a shot of fireball'",
    content: "ONLY AVAILABLE IN PAID PLANS",
    pubDate: "2025-02-14 18:11:00",
    pubDateTZ: "UTC",
    image_url:
      "https://www.bpmcdn.com/f/files/shared/feeds/gps/2024/08/web1_8082479_web1_170812-rda-m-hat--rda-rcmp-.jpg;w=960",
    source_id: "kelownacapnews",
    source_priority: 438678,
    source_name: "Kelowna Capital News",
    source_url: "https://www.kelownacapnews.com",
    source_icon: "https://i.bytvi.com/domain_icons/kelownacapnews.png",
    language: "english",
    country: ["canada"],
    category: ["top"],
    ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
    ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
    duplicate: true,
  },
  {
    article_id: "ff143c84a1cea1825af95e051c871593",
    title:
      "Grávida, Bia Miranda se envolve em briga e mulher agredida vai à delegacia: - Uma baita covardia",
    link: "https://www.dgabc.com.br/Noticia/4203826/gravida-bia-miranda-se-envolve-em-briga-e-mulher-agredida-vai-a-delegacia-uma-baita-covardia",
    keywords: ["cultura & lazer"],
    creator: null,
    video_url: null,
    description: null,
    content: "ONLY AVAILABLE IN PAID PLANS",
    pubDate: "2025-02-14 18:11:00",
    pubDateTZ: "UTC",
    image_url: null,
    source_id: "dgabc",
    source_priority: 1985812,
    source_name: "Diário Do Grande Abc",
    source_url: "https://www.dgabc.com.br",
    source_icon: null,
    language: "portuguese",
    country: ["brazil"],
    category: ["top"],
    ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
    ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
    duplicate: false,
  },
  {
    article_id: "2accca9df56e5ac9724186a3b7145606",
    title:
      "Salmon Arm woman loses licence after admitting to drinking on 'lunch break'",
    link: "https://www.vernonmorningstar.com/news/salmon-arm-woman-loses-licence-after-admitting-to-drinking-on-lunch-break-7823531",
    keywords: null,
    creator: ["Heather Black"],
    video_url: null,
    description: "Confessed to having 'several beers, and a shot of fireball'",
    content: "ONLY AVAILABLE IN PAID PLANS",
    pubDate: "2025-02-14 18:11:00",
    pubDateTZ: "UTC",
    image_url:
      "https://www.bpmcdn.com/f/files/shared/feeds/gps/2024/08/web1_8082479_web1_170812-rda-m-hat--rda-rcmp-.jpg;w=960",
    source_id: "vernonmorningstar",
    source_priority: 213574,
    source_name: "Vernon Morning Star",
    source_url: "https://www.vernonmorningstar.com",
    source_icon: "https://i.bytvi.com/domain_icons/vernonmorningstar.png",
    language: "english",
    country: ["canada"],
    category: ["top"],
    ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
    ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
    duplicate: false,
  },
  {
    article_id: "50bf48f2fde4eb6eec65615c386d5477",
    title: "Rozmowa USA-Ukraina dobiegła końca. Padły ważne słowa",
    link: "https://www.rmf24.pl/raporty/raport-wojna-z-rosja/news-rozmowa-usa-ukraina-dobiegla-konca-padly-wazne-slowa,nId,7913049",
    keywords: ["wojna w ukrainie"],
    creator: null,
    video_url: null,
    description:
      'Długo oczekiwana rozmowa dobiegła końca. W piątek po godz. 18:00 w Monachium zakończyło się spotkanie przedstawicieli Stanów Zjednoczonych i Ukrainy, z J.D. Vance\'em i Wołodymyrem Zełenskim na czele. Szczegółów nie podano, ale wiceprezydent USA zapewnił, że w Ukrainie niezbędny jest trwały pokój, a "nie taki, który będzie skutkował konfliktem w Europie Wschodniej za kilka lat".',
    content: "ONLY AVAILABLE IN PAID PLANS",
    pubDate: "2025-02-14 18:11:00",
    pubDateTZ: "UTC",
    image_url:
      "https://interia-s.pluscdn.pl/rozmowa-usa-ukraina-dobiegla-konca-padly-wazne-slowa/000KLR254DLTB73S-C307.jpg",
    source_id: "rmf24",
    source_priority: 250858,
    source_name: "Rmf24",
    source_url: "https://www.rmf24.pl",
    source_icon: "https://i.bytvi.com/domain_icons/rmf24.png",
    language: "polish",
    country: ["poland"],
    category: ["top"],
    ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
    ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
    duplicate: false,
  },
];
